export const CitiesOptions = [
    { value: 1, label: "Arica" },
    { value: 2, label: "Parinacota" },
    { value: 3, label: "Iquique" },
    { value: 4, label: "El Tamarugal" },
    { value: 5, label: "Tocopilla" },
    { value: 6, label: "El Loa" },
    { value: 7, label: "Antofagasta" },
    { value: 8, label: "Chañaral" },
    { value: 9, label: "Copiapó" },
    { value: 10, label: "Huasco" },
    { value: 11, label: "Elqui" },
    { value: 12, label: "Limarí" },
    { value: 13, label: "Choapa" },
    { value: 14, label: "Petorca" },
    { value: 15, label: "Los Andes" },
    { value: 16, label: "San Felipe de Aconcagua" },
    { value: 17, label: "Quillota" },
    { value: 18, label: "Valparaiso" },
    { value: 19, label: "San Antonio" },
    { value: 20, label: "Isla de Pascua" },
    { value: 21, label: "Marga Marga" },
    { value: 22, label: "Chacabuco" },
    { value: 23, label: "Santiago" },
    { value: 24, label: "Cordillera" },
    { value: 25, label: "Maipo" },
    { value: 26, label: "Melipilla" },
    { value: 27, label: "Talagante" },
    { value: 28, label: "Cachapoal" },
    { value: 29, label: "Colchagua" },
    { value: 30, label: "Cardenal Caro" },
    { value: 31, label: "Curicó" },
    { value: 32, label: "Talca" },
    { value: 33, label: "Linares" },
    { value: 34, label: "Cauquenes" },
    { value: 35, label: "Diguillín" },
    { value: 36, label: "Itata" },
    { value: 37, label: "Punilla" },
    { value: 38, label: "Bio Bío" },
    { value: 39, label: "Concepción" },
    { value: 40, label: "Arauco" },
    { value: 41, label: "Malleco" },
    { value: 42, label: "Cautín" },
    { value: 43, label: "Valdivia" },
    { value: 44, label: "Ranco" },
    { value: 45, label: "Osorno" },
    { value: 46, label: "Llanquihue" },
    { value: 47, label: "Chiloé" },
    { value: 48, label: "Palena" },
    { value: 49, label: "Coyhaique" },
    { value: 50, label: "Aysén" },
    { value: 51, label: "General Carrera" },
    { value: 52, label: "Capitán Prat" },
    { value: 53, label: "Última Esperanza" },
    { value: 54, label: "Magallanes" },
    { value: 55, label: "Tierra del Fuego" },
    { value: 56, label: "Antártica Chilena" },
];


export const communes = [
    { id: 1, name: 'Arica', cityId: 1 },
  { id: 2, name: 'Camarones', cityId: 1 },
  { id: 3, name: 'General Lagos', cityId: 2 },
  { id: 4, name: 'Putre', cityId: 2 },
  { id: 5, name: 'Alto Hospicio', cityId: 3 },
  { id: 6, name: 'Iquique', cityId: 3 },
  { id: 7, name: 'Camiña', cityId: 4 },
  { id: 8, name: 'Colchane', cityId: 4 },
  { id: 9, name: 'Huara', cityId: 4 },
  { id: 10, name: 'Pica', cityId: 4 },
  { id: 11, name: 'Pozo Almonte', cityId: 4 },
  { id: 12, name: 'Tocopilla', cityId: 5 },
  { id: 13, name: 'María Elena', cityId: 5 },
  { id: 14, name: 'Calama', cityId: 6 },
  { id: 15, name: 'Ollague', cityId: 6 },
  { id: 16, name: 'San Pedro de Atacama', cityId: 6 },
  { id: 17, name: 'Antofagasta', cityId: 7 },
  { id: 18, name: 'Mejillones', cityId: 7 },
  { id: 19, name: 'Sierra Gorda', cityId: 7 },
  { id: 20, name: 'Taltal', cityId: 7 },
  { id: 21, name: 'Chañaral', cityId: 8 },
  { id: 22, name: 'Diego de Almagro', cityId: 8 },
  { id: 23, name: 'Copiapó', cityId: 9 },
  { id: 24, name: 'Caldera', cityId: 9 },
  { id: 25, name: 'Tierra Amarilla', cityId: 9 },
  { id: 26, name: 'Vallenar', cityId: 10 },
  { id: 27, name: 'Alto del Carmen', cityId: 10 },
  { id: 28, name: 'Freirina', cityId: 10 },
  { id: 29, name: 'Huasco', cityId: 10 },
  { id: 30, name: 'La Serena', cityId: 11 },
  { id: 31, name: 'Coquimbo', cityId: 11 },
  { id: 32, name: 'Andacollo', cityId: 11 },
  { id: 33, name: 'La Higuera', cityId: 11 },
  { id: 34, name: 'Paihuano', cityId: 11 },
  { id: 35, name: 'Vicuña', cityId: 11 },
  { id: 36, name: 'Ovalle', cityId: 12 },
  { id: 37, name: 'Combarbalá', cityId: 12 },
  { id: 38, name: 'Monte Patria', cityId: 12 },
  { id: 39, name: 'Punitaqui', cityId: 12 },
  { id: 40, name: 'Río Hurtado', cityId: 12 },
  { id: 41, name: 'Illapel', cityId: 13 },
  { id: 42, name: 'Canela', cityId: 13 },
  { id: 43, name: 'Los Vilos', cityId: 13 },
  { id: 44, name: 'Salamanca', cityId: 13 },
  { id: 45, name: 'La Ligua', cityId: 14 },
  { id: 46, name: 'Cabildo', cityId: 14 },
  { id: 47, name: 'Zapallar', cityId: 14 },
  { id: 48, name: 'Papudo', cityId: 14 },
  { id: 49, name: 'Petorca', cityId: 14 },
  { id: 50, name: 'Los Andes', cityId: 15 },
  { id: 51, name: 'San Esteban', cityId: 15 },
  { id: 52, name: 'Calle Larga', cityId: 15 },
  { id: 53, name: 'Rinconada', cityId: 15 },
  { id: 54, name: 'San Felipe', cityId: 16 },
  { id: 55, name: 'Llaillay', cityId: 16 },
  { id: 56, name: 'Putaendo', cityId: 16 },
  { id: 57, name: 'Santa María', cityId: 16 },
  { id: 58, name: 'Catemu', cityId: 16 },
  { id: 59, name: 'Panquehue', cityId: 16 },
  { id: 60, name: 'Quillota', cityId: 17 },
  { id: 61, name: 'La Cruz', cityId: 17 },
  { id: 62, name: 'La Calera', cityId: 17 },
  { id: 63, name: 'Nogales', cityId: 17 },
  { id: 64, name: 'Hijuelas', cityId: 17 },
  { id: 65, name: 'Valparaíso', cityId: 18 },
  { id: 66, name: 'Viña del Mar', cityId: 18 },
  { id: 67, name: 'Concón', cityId: 18 },
  { id: 68, name: 'Quintero', cityId: 18 },
  { id: 69, name: 'Puchuncaví', cityId: 18 },
  { id: 70, name: 'Casablanca', cityId: 18 },
  { id: 71, name: 'Juan Fernández', cityId: 18 },
  { id: 72, name: 'San Antonio', cityId: 19 },
  { id: 73, name: 'Cartagena', cityId: 19 },
  { id: 74, name: 'El Tabo', cityId: 19 },
  { id: 75, name: 'El Quisco', cityId: 19 },
  { id: 76, name: 'Algarrobo', cityId: 19 },
  { id: 77, name: 'Santo Domingo', cityId: 19 },
  { id: 78, name: 'Isla de Pascua', cityId: 20 },
  { id: 79, name: 'Quilpué', cityId: 21 },
  { id: 80, name: 'Limache', cityId: 21 },
  { id: 81, name: 'Olmué', cityId: 21 },
  { id: 82, name: 'Villa Alemana', cityId: 21 },
  { id: 83, name: 'Colina', cityId: 22 },
  { id: 84, name: 'Lampa', cityId: 22 },
  { id: 85, name: 'Tiltil', cityId: 22 },
  { id: 86, name: 'Santiago', cityId: 23 },
  { id: 87, name: 'Vitacura', cityId: 23 },
  { id: 88, name: 'San Ramón', cityId: 23 },
  { id: 89, name: 'San Miguel', cityId: 23 },
  { id: 90, name: 'San Joaquín', cityId: 23 },
  { id: 91, name: 'Renca', cityId: 23 },
  { id: 92, name: 'Recoleta', cityId: 23 },
  { id: 93, name: 'Quinta Normal', cityId: 23 },
  { id: 94, name: 'Quilicura', cityId: 23 },
  { id: 95, name: 'Pudahuel', cityId: 23 },
  { id: 96, name: 'Providencia', cityId: 23 },
  { id: 97, name: 'Peñalolén', cityId: 23 },
  { id: 98, name: 'Pedro Aguirre Cerda', cityId: 23 },
  { id: 99, name: 'Ñuñoa', cityId: 23 },
  { id: 100, name: 'Maipú', cityId: 23 },
  { id: 101, name: 'Macul', cityId: 23 },
  { id: 102, name: 'Lo Prado', cityId: 23 },
  { id: 103, name: 'Lo Espejo', cityId: 23 },
  { id: 104, name: 'Lo Barnechea', cityId: 23 },
  { id: 105, name: 'Las Condes', cityId: 23 },
  { id: 106, name: 'La Reina', cityId: 23 },
  { id: 107, name: 'La Pintana', cityId: 23 },
  { id: 108, name: 'La Granja', cityId: 23 },
  { id: 109, name: 'La Florida', cityId: 23 },
  { id: 110, name: 'La Cisterna', cityId: 23 },
  { id: 111, name: 'Independencia', cityId: 23 },
  { id: 112, name: 'Huechuraba', cityId: 23 },
  { id: 113, name: 'Estación Central', cityId: 23 },
  { id: 114, name: 'El Bosque', cityId: 23 },
  { id: 115, name: 'Conchalí', cityId: 23 },
  { id: 116, name: 'Cerro Navia', cityId: 23 },
  { id: 117, name: 'Cerrillos', cityId: 23 },
  { id: 118, name: 'Puente Alto', cityId: 24 },
  { id: 119, name: 'San José de Maipo', cityId: 24 },
  { id: 120, name: 'Pirque', cityId: 24 },
  { id: 121, name: 'San Bernardo', cityId: 25 },
  { id: 122, name: 'Buin', cityId: 25 },
  { id: 123, name: 'Paine', cityId: 25 },
  { id: 124, name: 'Calera de Tango', cityId: 25 },
  { id: 125, name: 'Melipilla', cityId: 26 },
  { id: 126, name: 'Alhué', cityId: 26 },
  { id: 127, name: 'Curacaví', cityId: 26 },
  { id: 128, name: 'María Pinto', cityId: 26 },
  { id: 129, name: 'San Pedro', cityId: 26 },
  { id: 130, name: 'Isla de Maipo', cityId: 27 },
  { id: 131, name: 'El Monte', cityId: 27 },
  { id: 132, name: 'Padre Hurtado', cityId: 27 },
  { id: 133, name: 'Peñaflor', cityId: 27 },
  { id: 134, name: 'Talagante', cityId: 27 },
  { id: 135, name: 'Codegua', cityId: 28 },
  { id: 136, name: 'Coínco', cityId: 28 },
  { id: 137, name: 'Coltauco', cityId: 28 },
  { id: 138, name: 'Doñihue', cityId: 28 },
  { id: 139, name: 'Graneros', cityId: 28 },
  { id: 140, name: 'Las Cabras', cityId: 28 },
  { id: 141, name: 'Machalí', cityId: 28 },
  { id: 142, name: 'Malloa', cityId: 28 },
  { id: 143, name: 'Mostazal', cityId: 28 },
  { id: 144, name: 'Olivar', cityId: 28 },
  { id: 145, name: 'Peumo', cityId: 28 },
  { id: 146, name: 'Pichidegua', cityId: 28 },
  { id: 147, name: 'Quinta de Tilcoco', cityId: 28 },
  { id: 148, name: 'Rancagua', cityId: 28 },
  { id: 149, name: 'Rengo', cityId: 28 },
  { id: 150, name: 'Requínoa', cityId: 28 },
  { id: 151, name: 'San Vicente de Tagua Tagua', cityId: 28 },
  { id: 152, name: 'Chépica', cityId: 29 },
  { id: 153, name: 'Chimbarongo', cityId: 29 },
  { id: 154, name: 'Lolol', cityId: 29 },
  { id: 155, name: 'Nancagua', cityId: 29 },
  { id: 156, name: 'Palmilla', cityId: 29 },
  { id: 157, name: 'Peralillo', cityId: 29 },
  { id: 158, name: 'Placilla', cityId: 29 },
  { id: 159, name: 'Pumanque', cityId: 29 },
  { id: 160, name: 'San Fernando', cityId: 29 },
  { id: 161, name: 'Santa Cruz', cityId: 29 },
  { id: 162, name: 'La Estrella', cityId: 30 },
  { id: 163, name: 'Litueche', cityId: 30 },
  { id: 164, name: 'Marchigüe', cityId: 30 },
  { id: 165, name: 'Navidad', cityId: 30 },
  { id: 166, name: 'Paredones', cityId: 30 },
  { id: 167, name: 'Pichilemu', cityId: 30 },
  { id: 168, name: 'Curicó', cityId: 31 },
  { id: 169, name: 'Hualañé', cityId: 31 },
  { id: 170, name: 'Licantén', cityId: 31 },
  { id: 171, name: 'Molina', cityId: 31 },
  { id: 172, name: 'Rauco', cityId: 31 },
  { id: 173, name: 'Romeral', cityId: 31 },
  { id: 174, name: 'Sagrada Familia', cityId: 31 },
  { id: 175, name: 'Teno', cityId: 31 },
  { id: 176, name: 'Vichuquén', cityId: 31 },
  { id: 177, name: 'Talca', cityId: 32 },
  { id: 178, name: 'San Clemente', cityId: 32 },
  { id: 179, name: 'Pelarco', cityId: 32 },
  { id: 180, name: 'Pencahue', cityId: 32 },
  { id: 181, name: 'Maule', cityId: 32 },
  { id: 182, name: 'San Rafael', cityId: 32 },
  { id: 183, name: 'Curepto', cityId: 33 },
  { id: 184, name: 'Constitución', cityId: 32 },
  { id: 185, name: 'Empedrado', cityId: 32 },
  { id: 186, name: 'Río Claro', cityId: 32 },
  { id: 187, name: 'Linares', cityId: 33 },
  { id: 188, name: 'San Javier', cityId: 33 },
  { id: 189, name: 'Parral', cityId: 33 },
  { id: 190, name: 'Villa Alegre', cityId: 33 },
  { id: 191, name: 'Longaví', cityId: 33 },
  { id: 192, name: 'Colbún', cityId: 33 },
  { id: 193, name: 'Retiro', cityId: 33 },
  { id: 194, name: 'Yerbas Buenas', cityId: 33 },
  { id: 195, name: 'Cauquenes', cityId: 34 },
  { id: 196, name: 'Chanco', cityId: 34 },
  { id: 197, name: 'Pelluhue', cityId: 34 },
  { id: 198, name: 'Bulnes', cityId: 35 },
  { id: 199, name: 'Chillán', cityId: 35 },
  { id: 200, name: 'Chillán Viejo', cityId: 35 },
  { id: 201, name: 'El Carmen', cityId: 35 },
  { id: 202, name: 'Pemuco', cityId: 35 },
  { id: 203, name: 'Pinto', cityId: 35 },
  { id: 204, name: 'Quillón', cityId: 35 },
  { id: 205, name: 'San Ignacio', cityId: 35 },
  { id: 206, name: 'Yungay', cityId: 35 },
  { id: 207, name: 'Cobquecura', cityId: 36 },
  { id: 208, name: 'Coelemu', cityId: 36 },
  { id: 209, name: 'Ninhue', cityId: 36 },
  { id: 210, name: 'Portezuelo', cityId: 36 },
  { id: 211, name: 'Quirihue', cityId: 36 },
  { id: 212, name: 'Ránquil', cityId: 36 },
  { id: 213, name: 'Treguaco', cityId: 36 },
  { id: 214, name: 'San Carlos', cityId: 37 },
  { id: 215, name: 'Coihueco', cityId: 37 },
  { id: 216, name: 'San Nicolás', cityId: 37 },
  { id: 217, name: 'Ñiquén', cityId: 37 },
  { id: 218, name: 'San Fabián', cityId: 37 },
  { id: 219, name: 'Alto Biobío', cityId: 38 },
  { id: 220, name: 'Antuco', cityId: 38 },
  { id: 221, name: 'Cabrero', cityId: 38 },
  { id: 222, name: 'Laja', cityId: 38 },
  { id: 223, name: 'Los Ángeles', cityId: 38 },
  { id: 224, name: 'Mulchén', cityId: 38 },
  { id: 225, name: 'Nacimiento', cityId: 38 },
  { id: 226, name: 'Negrete', cityId: 38 },
  { id: 227, name: 'Quilaco', cityId: 38 },
  { id: 228, name: 'Quilleco', cityId: 38 },
  { id: 229, name: 'San Rosendo', cityId: 38 },
  { id: 230, name: 'Santa Bárbara', cityId: 38 },
  { id: 231, name: 'Tucapel', cityId: 38 },
  { id: 232, name: 'Yumbel', cityId: 38 },
  { id: 233, name: 'Concepción', cityId: 39 },
  { id: 234, name: 'Coronel', cityId: 39 },
  { id: 235, name: 'Chiguayante', cityId: 39 },
  { id: 236, name: 'Florida', cityId: 39 },
  { id: 237, name: 'Hualpén', cityId: 39 },
  { id: 238, name: 'Hualqui', cityId: 39 },
  { id: 239, name: 'Lota', cityId: 39 },
  { id: 240, name: 'Penco', cityId: 39 },
  { id: 241, name: 'San Pedro de La Paz', cityId: 39 },
  { id: 242, name: 'Santa Juana', cityId: 39 },
  { id: 243, name: 'Talcahuano', cityId: 39 },
  { id: 244, name: 'Tomé', cityId: 39 },
  { id: 245, name: 'Arauco', cityId: 40 },
  { id: 246, name: 'Cañete', cityId: 40 },
  { id: 247, name: 'Contulmo', cityId: 40 },
  { id: 248, name: 'Curanilahue', cityId: 40 },
  { id: 249, name: 'Lebu', cityId: 40 },
  { id: 250, name: 'Los Álamos', cityId: 40 },
  { id: 251, name: 'Tirúa', cityId: 40 },
  { id: 252, name: 'Angol', cityId: 41 },
  { id: 253, name: 'Collipulli', cityId: 41 },
  { id: 254, name: 'Curacautín', cityId: 41 },
  { id: 255, name: 'Ercilla', cityId: 41 },
  { id: 256, name: 'Lonquimay', cityId: 41 },
  { id: 257, name: 'Los Sauces', cityId: 41 },
  { id: 258, name: 'Lumaco', cityId: 41 },
  { id: 259, name: 'Purén', cityId: 41 },
  { id: 260, name: 'Renaico', cityId: 41 },
  { id: 261, name: 'Traiguén', cityId: 41 },
  { id: 262, name: 'Victoria', cityId: 41 },
  { id: 263, name: 'Temuco', cityId: 42 },
  { id: 264, name: 'Carahue', cityId: 42 },
  { id: 265, name: 'Cholchol', cityId: 42 },
  { id: 266, name: 'Cunco', cityId: 42 },
  { id: 267, name: 'Curarrehue', cityId: 42 },
  { id: 268, name: 'Freire', cityId: 42 },
  { id: 269, name: 'Galvarino', cityId: 42 },
  { id: 270, name: 'Gorbea', cityId: 42 },
  { id: 271, name: 'Lautaro', cityId: 42 },
  { id: 272, name: 'Loncoche', cityId: 42 },
  { id: 273, name: 'Melipeuco', cityId: 42 },
  { id: 274, name: 'Nueva Imperial', cityId: 42 },
  { id: 275, name: 'Padre Las Casas', cityId: 42 },
  { id: 276, name: 'Perquenco', cityId: 42 },
  { id: 277, name: 'Pitrufquén', cityId: 42 },
  { id: 278, name: 'Pucón', cityId: 42 },
  { id: 279, name: 'Saavedra', cityId: 42 },
  { id: 280, name: 'Teodoro Schmidt', cityId: 42 },
  { id: 281, name: 'Toltén', cityId: 42 },
  { id: 282, name: 'Vilcún', cityId: 42 },
  { id: 283, name: 'Villarrica', cityId: 42 },
  { id: 284, name: 'Valdivia', cityId: 43 },
  { id: 285, name: 'Corral', cityId: 43 },
  { id: 286, name: 'Lanco', cityId: 43 },
  { id: 287, name: 'Los Lagos', cityId: 43 },
  { id: 288, name: 'Máfil', cityId: 43 },
  { id: 289, name: 'Mariquina', cityId: 43 },
  { id: 290, name: 'Paillaco', cityId: 43 },
  { id: 291, name: 'Panguipulli', cityId: 43 },
  { id: 292, name: 'La Unión', cityId: 44 },
  { id: 293, name: 'Futrono', cityId: 44 },
  { id: 294, name: 'Lago Ranco', cityId: 44 },
  { id: 295, name: 'Río Bueno', cityId: 44 },
  { id: 296, name: 'Osorno', cityId: 45 },
  { id: 297, name: 'Puerto Octay', cityId: 45 },
  { id: 298, name: 'Purranque', cityId: 45 },
  { id: 299, name: 'Puyehue', cityId: 45 },
  { id: 300, name: 'Río Negro', cityId: 45 },
  { id: 301, name: 'San Juan de la Costa', cityId: 45 },
  { id: 302, name: 'San Pablo', cityId: 45 },
  { id: 303, name: 'Calbuco', cityId: 46 },
  { id: 304, name: 'Cochamó', cityId: 46 },
  { id: 305, name: 'Fresia', cityId: 46 },
  { id: 306, name: 'Frutillar', cityId: 46 },
  { id: 307, name: 'Llanquihue', cityId: 46 },
  { id: 308, name: 'Los Muermos', cityId: 46 },
  { id: 309, name: 'Maullín', cityId: 46 },
  { id: 310, name: 'Puerto Montt', cityId: 46 },
  { id: 311, name: 'Puerto Varas', cityId: 46 },
  { id: 312, name: 'Ancud', cityId: 47 },
  { id: 313, name: 'Castro', cityId: 47 },
  { id: 314, name: 'Chonchi', cityId: 47 },
  { id: 315, name: 'Curaco de Vélez', cityId: 47 },
  { id: 316, name: 'Dalcahue', cityId: 47 },
  { id: 317, name: 'Puqueldón', cityId: 47 },
  { id: 318, name: 'Queilén', cityId: 47 },
  { id: 319, name: 'Quellón', cityId: 47 },
  { id: 320, name: 'Quemchi', cityId: 47 },
  { id: 321, name: 'Quinchao', cityId: 47 },
  { id: 322, name: 'Chaitén', cityId: 48 },
  { id: 323, name: 'Futaleufú', cityId: 48 },
  { id: 324, name: 'Hualaihué', cityId: 48 },
  { id: 325, name: 'Palena', cityId: 48 },
  { id: 326, name: 'Lago Verde', cityId: 49 },
  { id: 327, name: 'Coihaique', cityId: 49 },
  { id: 328, name: 'Aysén', cityId: 50 },
  { id: 329, name: 'Cisnes', cityId: 50 },
  { id: 330, name: 'Guaitecas', cityId: 50 },
  { id: 331, name: 'Río Ibáñez', cityId: 51 },
  { id: 332, name: 'Chile Chico', cityId: 51 },
  { id: 333, name: 'Cochrane', cityId: 52 },
  { id: 334, name: 'O Higgins', cityId: 52 },
  { id: 335, name: 'Tortel', cityId: 52 },
  { id: 336, name: 'Natales', cityId: 53 },
  { id: 337, name: 'Torres del Paine', cityId: 53 },
  { id: 338, name: 'Laguna Blanca', cityId: 54 },
  { id: 339, name: 'Punta Arenas', cityId: 54 },
  { id: 340, name: 'Río Verde', cityId: 54 },
  { id: 341, name: 'San Gregorio', cityId: 54 },
  { id: 342, name: 'Porvenir', cityId: 55 },
  { id: 343, name: 'Primavera', cityId: 55 },
  { id: 344, name: 'Timaukel', cityId: 55 },
  { id: 345, name: 'Cabo de Hornos', cityId: 56 },
  { id: 346, name: 'Antártica', cityId: 56 }
];

export const DaysOptions = [
  { value: 1, label: "lunes" },
  { value: 2, label: "martes" },
  { value: 3, label: "miércoles" },
  { value: 4, label: "jueves" },
  { value: 5, label: "viernes" },
  { value: 6, label: "sábado" },
  { value: 7, label: "domingo" }
]

export const StatusSubscriptionOptions = [
  { value: "active", label: "Activa" },
  { value: "inactive", label: "Inactiva" },
  { value: "suspend", label: "Suspendida" },
  { value: "soon_to_expire", label: "Pronto a vencer(5 días)" },
]
