// This file is auto-generated by @hey-api/openapi-ts

export const AdministratorCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        genre: {
            type: 'string',
            title: 'Genre'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        rut: {
            type: 'string',
            title: 'Rut'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        max_users: {
            type: 'integer',
            title: 'Max Users'
        },
        licence_type: {
            type: 'string',
            title: 'Licence Type'
        },
        access_level: {
            type: 'integer',
            title: 'Access Level'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'genre', 'email', 'password', 'rut', 'max_users', 'licence_type', 'access_level'],
    title: 'AdministratorCreate'
} as const;

export const Body_authenticate_user_auth_token_postSchema = {
    properties: {
        grant_type: {
            anyOf: [
                {
                    type: 'string',
                    pattern: 'password'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Grant Type'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        scope: {
            type: 'string',
            title: 'Scope',
            default: ''
        },
        client_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Id'
        },
        client_secret: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Client Secret'
        }
    },
    type: 'object',
    required: ['username', 'password'],
    title: 'Body_authenticate_user_auth_token_post'
} as const;

export const DisciplineSchema = {
    properties: {
        discipline_name: {
            type: 'string',
            title: 'Discipline Name'
        },
        trainer_id: {
            type: 'string',
            title: 'Trainer Id'
        },
        student_max_quantity: {
            type: 'integer',
            title: 'Student Max Quantity'
        },
        discipline_id: {
            type: 'integer',
            title: 'Discipline Id'
        }
    },
    type: 'object',
    required: ['discipline_name', 'trainer_id', 'student_max_quantity', 'discipline_id'],
    title: 'Discipline'
} as const;

export const DisciplineBaseSchema = {
    properties: {
        discipline_name: {
            type: 'string',
            title: 'Discipline Name'
        },
        trainer_id: {
            type: 'string',
            title: 'Trainer Id'
        },
        student_max_quantity: {
            type: 'integer',
            title: 'Student Max Quantity'
        }
    },
    type: 'object',
    required: ['discipline_name', 'trainer_id', 'student_max_quantity'],
    title: 'DisciplineBase'
} as const;

export const DisciplineCreateSchema = {
    properties: {
        discipline_name: {
            type: 'string',
            title: 'Discipline Name'
        },
        trainer_id: {
            type: 'string',
            title: 'Trainer Id'
        },
        student_max_quantity: {
            type: 'integer',
            title: 'Student Max Quantity'
        }
    },
    type: 'object',
    required: ['discipline_name', 'trainer_id', 'student_max_quantity'],
    title: 'DisciplineCreate'
} as const;

export const DisciplineUpdateSchema = {
    properties: {
        discipline_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discipline Name'
        },
        trainer_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Trainer Id'
        },
        student_max_quantity: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Max Quantity'
        }
    },
    type: 'object',
    title: 'DisciplineUpdate'
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const ListDisciplineResponseSchema = {
    properties: {
        disciplines: {
            items: {
                '$ref': '#/components/schemas/Discipline'
            },
            type: 'array',
            title: 'Disciplines'
        }
    },
    type: 'object',
    required: ['disciplines'],
    title: 'ListDisciplineResponse'
} as const;

export const ListPlanSchema = {
    properties: {
        plans: {
            items: {
                '$ref': '#/components/schemas/PlanResponse'
            },
            type: 'array',
            title: 'Plans'
        }
    },
    type: 'object',
    required: ['plans'],
    title: 'ListPlan'
} as const;

export const ListScheduleSchema = {
    properties: {
        schedules: {
            items: {
                '$ref': '#/components/schemas/ScheduleResponse'
            },
            type: 'array',
            title: 'Schedules'
        }
    },
    type: 'object',
    required: ['schedules'],
    title: 'ListSchedule'
} as const;

export const ListScheduleForDisciplineSchema = {
    properties: {
        schedules: {
            items: {
                '$ref': '#/components/schemas/ScheduleForDisciplineResponse'
            },
            type: 'array',
            title: 'Schedules'
        }
    },
    type: 'object',
    required: ['schedules'],
    title: 'ListScheduleForDiscipline'
} as const;

export const ListSportCenterSchema = {
    properties: {
        sportcenters: {
            items: {
                '$ref': '#/components/schemas/SportCenterResponse'
            },
            type: 'array',
            title: 'Sportcenters'
        }
    },
    type: 'object',
    required: ['sportcenters'],
    title: 'ListSportCenter'
} as const;

export const ListStudentSportcenterSchema = {
    properties: {
        students_sportcenter: {
            items: {
                '$ref': '#/components/schemas/StudentSportcenter'
            },
            type: 'array',
            title: 'Students Sportcenter'
        }
    },
    type: 'object',
    required: ['students_sportcenter'],
    title: 'ListStudentSportcenter'
} as const;

export const ListTrainersSchema = {
    properties: {
        trainers: {
            items: {
                '$ref': '#/components/schemas/TrainerResponse'
            },
            type: 'array',
            title: 'Trainers'
        }
    },
    type: 'object',
    required: ['trainers'],
    title: 'ListTrainers'
} as const;

export const PlanCreateSchema = {
    properties: {
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        },
        plan_name: {
            type: 'string',
            title: 'Plan Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        classes_quantity: {
            type: 'integer',
            title: 'Classes Quantity'
        },
        duration: {
            type: 'integer',
            title: 'Duration'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        }
    },
    type: 'object',
    required: ['discipline_id', 'plan_name', 'description', 'classes_quantity', 'duration', 'price', 'is_active'],
    title: 'PlanCreate'
} as const;

export const PlanResponseSchema = {
    properties: {
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        },
        plan_name: {
            type: 'string',
            title: 'Plan Name'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        classes_quantity: {
            type: 'integer',
            title: 'Classes Quantity'
        },
        duration: {
            type: 'integer',
            title: 'Duration'
        },
        price: {
            type: 'integer',
            title: 'Price'
        },
        is_active: {
            type: 'boolean',
            title: 'Is Active'
        },
        plan_id: {
            type: 'integer',
            title: 'Plan Id'
        }
    },
    type: 'object',
    required: ['discipline_id', 'plan_name', 'description', 'classes_quantity', 'duration', 'price', 'is_active', 'plan_id'],
    title: 'PlanResponse'
} as const;

export const PlanUpdateSchema = {
    properties: {
        discipline_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discipline Id'
        },
        plan_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Plan Name'
        },
        description: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Description'
        },
        classes_quantity: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Classes Quantity'
        },
        duration: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Duration'
        },
        price: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Price'
        },
        is_active: {
            anyOf: [
                {
                    type: 'boolean'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Is Active'
        }
    },
    type: 'object',
    title: 'PlanUpdate'
} as const;

export const ScheduleCreateSchema = {
    properties: {
        student_id: {
            type: 'string',
            title: 'Student Id'
        },
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        },
        sport_center_id: {
            type: 'string',
            title: 'Sport Center Id'
        },
        date_hour: {
            type: 'string',
            title: 'Date Hour'
        },
        creator_id: {
            type: 'string',
            title: 'Creator Id'
        }
    },
    type: 'object',
    required: ['student_id', 'discipline_id', 'sport_center_id', 'date_hour', 'creator_id'],
    title: 'ScheduleCreate'
} as const;

export const ScheduleForDisciplineCreateSchema = {
    properties: {
        day_id: {
            type: 'string',
            title: 'Day Id'
        },
        hour_start_class: {
            type: 'string',
            title: 'Hour Start Class'
        },
        hour_end_class: {
            type: 'string',
            title: 'Hour End Class'
        },
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        }
    },
    type: 'object',
    required: ['day_id', 'hour_start_class', 'hour_end_class', 'discipline_id'],
    title: 'ScheduleForDisciplineCreate'
} as const;

export const ScheduleForDisciplineResponseSchema = {
    properties: {
        day_id: {
            type: 'string',
            title: 'Day Id'
        },
        hour_start_class: {
            type: 'string',
            title: 'Hour Start Class'
        },
        hour_end_class: {
            type: 'string',
            title: 'Hour End Class'
        },
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        },
        schedule_for_discipline_id: {
            type: 'integer',
            title: 'Schedule For Discipline Id'
        }
    },
    type: 'object',
    required: ['day_id', 'hour_start_class', 'hour_end_class', 'discipline_id', 'schedule_for_discipline_id'],
    title: 'ScheduleForDisciplineResponse'
} as const;

export const ScheduleForDisciplineUpdateSchema = {
    properties: {
        day_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Day Id'
        },
        hour_start_class: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hour Start Class'
        },
        hour_end_class: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Hour End Class'
        },
        discipline_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discipline Id'
        }
    },
    type: 'object',
    title: 'ScheduleForDisciplineUpdate'
} as const;

export const ScheduleResponseSchema = {
    properties: {
        student_id: {
            type: 'string',
            title: 'Student Id'
        },
        discipline_id: {
            type: 'string',
            title: 'Discipline Id'
        },
        sport_center_id: {
            type: 'string',
            title: 'Sport Center Id'
        },
        date_hour: {
            type: 'string',
            title: 'Date Hour'
        },
        creator_id: {
            type: 'string',
            title: 'Creator Id'
        },
        schedule_id: {
            type: 'integer',
            title: 'Schedule Id'
        }
    },
    type: 'object',
    required: ['student_id', 'discipline_id', 'sport_center_id', 'date_hour', 'creator_id', 'schedule_id'],
    title: 'ScheduleResponse'
} as const;

export const ScheduleUpdateSchema = {
    properties: {
        student_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Student Id'
        },
        discipline_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Discipline Id'
        },
        sport_center_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sport Center Id'
        },
        date_hour: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Date Hour'
        }
    },
    type: 'object',
    title: 'ScheduleUpdate'
} as const;

export const SportCenterCreateSchema = {
    properties: {
        sport_center_name: {
            type: 'string',
            title: 'Sport Center Name'
        },
        city_id: {
            type: 'integer',
            title: 'City Id'
        },
        comuna_id: {
            type: 'integer',
            title: 'Comuna Id'
        },
        address: {
            type: 'string',
            title: 'Address'
        },
        phone: {
            type: 'integer',
            title: 'Phone'
        },
        mail: {
            type: 'string',
            format: 'email',
            title: 'Mail'
        },
        open_hour: {
            type: 'string',
            title: 'Open Hour'
        },
        close_hour: {
            type: 'string',
            title: 'Close Hour'
        }
    },
    type: 'object',
    required: ['sport_center_name', 'city_id', 'comuna_id', 'address', 'phone', 'mail', 'open_hour', 'close_hour'],
    title: 'SportCenterCreate'
} as const;

export const SportCenterResponseSchema = {
    properties: {
        sport_center_id: {
            type: 'integer',
            title: 'Sport Center Id'
        },
        sport_center_name: {
            type: 'string',
            title: 'Sport Center Name'
        },
        city_name: {
            type: 'string',
            title: 'City Name'
        },
        comuna_name: {
            type: 'string',
            title: 'Comuna Name'
        },
        address: {
            type: 'string',
            title: 'Address'
        },
        phone: {
            type: 'integer',
            title: 'Phone'
        },
        mail: {
            type: 'string',
            format: 'email',
            title: 'Mail'
        },
        open_hour: {
            type: 'string',
            title: 'Open Hour'
        },
        close_hour: {
            type: 'string',
            title: 'Close Hour'
        },
        owner_sport_center_name: {
            type: 'string',
            title: 'Owner Sport Center Name'
        }
    },
    type: 'object',
    required: ['sport_center_id', 'sport_center_name', 'city_name', 'comuna_name', 'address', 'phone', 'mail', 'open_hour', 'close_hour', 'owner_sport_center_name'],
    title: 'SportCenterResponse'
} as const;

export const SportCenterUpdateSchema = {
    properties: {
        sport_center_name: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Sport Center Name'
        },
        address: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Address'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        mail: {
            anyOf: [
                {
                    type: 'string',
                    format: 'email'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Mail'
        },
        open_hour: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Open Hour'
        },
        close_hour: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Close Hour'
        },
        city_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'City Id'
        },
        comuna_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Comuna Id'
        }
    },
    type: 'object',
    title: 'SportCenterUpdate'
} as const;

export const StudentCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        genre: {
            type: 'string',
            title: 'Genre'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        birthdate: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date-time'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Birthdate'
        },
        weight: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Weight'
        },
        height: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Height'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'genre', 'email', 'password'],
    title: 'StudentCreate'
} as const;

export const StudentSportcenterSchema = {
    properties: {
        sportcenter_id: {
            type: 'string',
            title: 'Sportcenter Id'
        },
        student_id: {
            type: 'string',
            title: 'Student Id'
        },
        plan_id: {
            type: 'string',
            title: 'Plan Id'
        },
        subscription_date: {
            type: 'string',
            format: 'date',
            title: 'Subscription Date'
        },
        expiration_date: {
            type: 'string',
            format: 'date',
            title: 'Expiration Date'
        },
        status: {
            allOf: [
                {
                    '$ref': '#/components/schemas/SubscriptionStatus'
                }
            ],
            default: 'active'
        },
        last_renewal_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Renewal Date'
        },
        student_sportcenter_id: {
            type: 'integer',
            title: 'Student Sportcenter Id'
        }
    },
    type: 'object',
    required: ['sportcenter_id', 'student_id', 'plan_id', 'subscription_date', 'expiration_date', 'student_sportcenter_id'],
    title: 'StudentSportcenter'
} as const;

export const StudentSportcenterCreateSchema = {
    properties: {
        sportcenter_id: {
            type: 'string',
            title: 'Sportcenter Id'
        },
        student_id: {
            type: 'string',
            title: 'Student Id'
        },
        plan_id: {
            type: 'string',
            title: 'Plan Id'
        },
        subscription_date: {
            type: 'string',
            format: 'date',
            title: 'Subscription Date'
        },
        expiration_date: {
            type: 'string',
            format: 'date',
            title: 'Expiration Date'
        },
        status: {
            allOf: [
                {
                    '$ref': '#/components/schemas/SubscriptionStatus'
                }
            ],
            default: 'active'
        },
        last_renewal_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Last Renewal Date'
        }
    },
    type: 'object',
    required: ['sportcenter_id', 'student_id', 'plan_id', 'subscription_date', 'expiration_date'],
    title: 'StudentSportcenterCreate'
} as const;

export const SubscriptionStatusSchema = {
    type: 'string',
    enum: ['active', 'inactive', 'canceled', 'suspended', 'pronto a vencer(5 días)'],
    title: 'SubscriptionStatus'
} as const;

export const TokenResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        },
        refresh_token: {
            type: 'string',
            title: 'Refresh Token'
        },
        token_type: {
            type: 'string',
            title: 'Token Type',
            default: 'Bearer'
        },
        expires_in: {
            type: 'integer',
            title: 'Expires In'
        }
    },
    type: 'object',
    required: ['access_token', 'refresh_token', 'expires_in'],
    title: 'TokenResponse'
} as const;

export const TrainerCreateSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        genre: {
            type: 'string',
            title: 'Genre'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        rut: {
            type: 'string',
            title: 'Rut'
        },
        salary: {
            type: 'integer',
            title: 'Salary'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'genre', 'email', 'password', 'rut', 'salary'],
    title: 'TrainerCreate'
} as const;

export const TrainerResponseSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        genre: {
            type: 'string',
            title: 'Genre'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        password: {
            type: 'string',
            title: 'Password'
        },
        user_id: {
            type: 'string',
            format: 'uuid',
            title: 'User Id'
        },
        rut: {
            type: 'string',
            title: 'Rut'
        },
        salary: {
            type: 'integer',
            title: 'Salary'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'genre', 'email', 'password', 'user_id', 'rut', 'salary'],
    title: 'TrainerResponse'
} as const;

export const TrainerSportcenterCreateSchema = {
    properties: {
        trainer_id: {
            type: 'string',
            title: 'Trainer Id'
        },
        sportcenter_id: {
            type: 'string',
            title: 'Sportcenter Id'
        }
    },
    type: 'object',
    required: ['trainer_id', 'sportcenter_id'],
    title: 'TrainerSportcenterCreate'
} as const;

export const TrainerUpdateSchema = {
    properties: {
        first_name: {
            type: 'string',
            title: 'First Name'
        },
        last_name: {
            type: 'string',
            title: 'Last Name'
        },
        genre: {
            type: 'string',
            title: 'Genre'
        },
        email: {
            type: 'string',
            format: 'email',
            title: 'Email'
        },
        phone: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Phone'
        },
        password: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Password'
        },
        rut: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Rut'
        },
        salary: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Salary'
        }
    },
    type: 'object',
    required: ['first_name', 'last_name', 'genre', 'email'],
    title: 'TrainerUpdate'
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;