// This file is auto-generated by @hey-api/openapi-ts

export type AdministratorCreate = {
    first_name: string;
    last_name: string;
    genre: string;
    email: string;
    phone?: (number | null);
    password: string;
    rut: string;
    address?: (string | null);
    max_users: number;
    licence_type: string;
    access_level: number;
};

export type Body_authenticate_user_auth_token_post = {
    grant_type?: (string | null);
    username: string;
    password: string;
    scope?: string;
    client_id?: (string | null);
    client_secret?: (string | null);
};

export type Discipline = {
    discipline_name: string;
    trainer_id: string;
    student_max_quantity: number;
    discipline_id: number;
};

export type DisciplineBase = {
    discipline_name: string;
    trainer_id: string;
    student_max_quantity: number;
};

export type DisciplineCreate = {
    discipline_name: string;
    trainer_id: string;
    student_max_quantity: number;
};

export type DisciplineUpdate = {
    discipline_name?: (string | null);
    trainer_id?: (string | null);
    student_max_quantity?: (number | null);
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type ListDisciplineResponse = {
    disciplines: Array<Discipline>;
};

export type ListPlan = {
    plans: Array<PlanResponse>;
};

export type ListSchedule = {
    schedules: Array<ScheduleResponse>;
};

export type ListScheduleForDiscipline = {
    schedules: Array<ScheduleForDisciplineResponse>;
};

export type ListSportCenter = {
    sportcenters: Array<SportCenterResponse>;
};

export type ListStudentSportcenter = {
    students_sportcenter: Array<StudentSportcenter>;
};

export type ListTrainers = {
    trainers: Array<TrainerResponse>;
};

export type PlanCreate = {
    discipline_id: string;
    plan_name: string;
    description: string;
    classes_quantity: number;
    duration: number;
    price: number;
    is_active: boolean;
};

export type PlanResponse = {
    discipline_id: string;
    plan_name: string;
    description: string;
    classes_quantity: number;
    duration: number;
    price: number;
    is_active: boolean;
    plan_id: number;
};

export type PlanUpdate = {
    discipline_id?: (string | null);
    plan_name?: (string | null);
    description?: (string | null);
    classes_quantity?: (number | null);
    duration?: (number | null);
    price?: (number | null);
    is_active?: (boolean | null);
};

export type ScheduleCreate = {
    student_id: string;
    discipline_id: string;
    sport_center_id: string;
    date_hour: string;
    creator_id: string;
};

export type ScheduleForDisciplineCreate = {
    day_id: string;
    hour_start_class: string;
    hour_end_class: string;
    discipline_id: string;
};

export type ScheduleForDisciplineResponse = {
    day_id: string;
    hour_start_class: string;
    hour_end_class: string;
    discipline_id: string;
    schedule_for_discipline_id: number;
};

export type ScheduleForDisciplineUpdate = {
    day_id?: (string | null);
    hour_start_class?: (string | null);
    hour_end_class?: (string | null);
    discipline_id?: (string | null);
};

export type ScheduleResponse = {
    student_id: string;
    discipline_id: string;
    sport_center_id: string;
    date_hour: string;
    creator_id: string;
    schedule_id: number;
};

export type ScheduleUpdate = {
    student_id?: (string | null);
    discipline_id?: (string | null);
    sport_center_id?: (string | null);
    date_hour?: (string | null);
};

export type SportCenterCreate = {
    sport_center_name: string;
    city_id: number;
    comuna_id: number;
    address: string;
    phone: number;
    mail: string;
    open_hour: string;
    close_hour: string;
};

export type SportCenterResponse = {
    sport_center_id: number;
    sport_center_name: string;
    city_name: string;
    comuna_name: string;
    address: string;
    phone: number;
    mail: string;
    open_hour: string;
    close_hour: string;
    owner_sport_center_name: string;
};

export type SportCenterUpdate = {
    sport_center_name?: (string | null);
    address?: (string | null);
    phone?: (number | null);
    mail?: (string | null);
    open_hour?: (string | null);
    close_hour?: (string | null);
    city_id?: (number | null);
    comuna_id?: (number | null);
};

export type StudentCreate = {
    first_name: string;
    last_name: string;
    genre: string;
    email: string;
    phone?: (number | null);
    password: string;
    birthdate?: (string | null);
    weight?: (string | null);
    height?: (string | null);
};

export type StudentSportcenter = {
    sportcenter_id: string;
    student_id: string;
    plan_id: string;
    subscription_date: string;
    expiration_date: string;
    status?: (SubscriptionStatus);
    last_renewal_date?: (string | null);
    student_sportcenter_id: number;
};

export type StudentSportcenterCreate = {
    sportcenter_id: string;
    student_id: string;
    plan_id: string;
    subscription_date: string;
    expiration_date: string;
    status?: (SubscriptionStatus);
    last_renewal_date?: (string | null);
};

export type SubscriptionStatus = 'active' | 'inactive' | 'canceled' | 'suspended' | 'pronto a vencer(5 días)';

export type TokenResponse = {
    access_token: string;
    refresh_token: string;
    token_type?: string;
    expires_in: number;
};

export type TrainerCreate = {
    first_name: string;
    last_name: string;
    genre: string;
    email: string;
    phone?: (number | null);
    password: string;
    rut: string;
    salary: number;
};

export type TrainerResponse = {
    first_name: string;
    last_name: string;
    genre: string;
    email: string;
    phone?: (number | null);
    password: string;
    user_id: string;
    rut: string;
    salary: number;
};

export type TrainerSportcenterCreate = {
    trainer_id: string;
    sportcenter_id: string;
};

export type TrainerUpdate = {
    first_name: string;
    last_name: string;
    genre: string;
    email: string;
    phone?: (number | null);
    password?: (string | null);
    rut?: (string | null);
    salary?: (number | null);
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type CreateUserUsersAdminCreatePostData = {
    body: AdministratorCreate;
};

export type CreateUserUsersAdminCreatePostResponse = (unknown);

export type CreateUserUsersAdminCreatePostError = (unknown | HTTPValidationError);

export type CreateUserStudentUsersStudentCreatePostData = {
    body: StudentCreate;
};

export type CreateUserStudentUsersStudentCreatePostResponse = (unknown);

export type CreateUserStudentUsersStudentCreatePostError = (unknown | HTTPValidationError);

export type AuthenticateUserAuthTokenPostData = {
    body: Body_authenticate_user_auth_token_post;
};

export type AuthenticateUserAuthTokenPostResponse = (TokenResponse);

export type AuthenticateUserAuthTokenPostError = (unknown | HTTPValidationError);

export type RefreshAccessTokenAuthRefreshPostData = {
    headers: {
        'refresh-token': string;
    };
};

export type RefreshAccessTokenAuthRefreshPostResponse = (unknown);

export type RefreshAccessTokenAuthRefreshPostError = (unknown | HTTPValidationError);

export type LogoutAuthLogoutPostResponse = (unknown);

export type LogoutAuthLogoutPostError = (unknown);

export type GetAdminsAdminAdminAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type GetAdminsAdminAdminAllGetResponse = (unknown);

export type GetAdminsAdminAdminAllGetError = (unknown | HTTPValidationError);

export type AdminDashboardAdminAdminDashboardGetData = {
    query?: {
        db?: unknown;
    };
};

export type AdminDashboardAdminAdminDashboardGetResponse = (unknown);

export type AdminDashboardAdminAdminDashboardGetError = (unknown | HTTPValidationError);

export type CreateUserTrainerAdminTrainerCreatePostData = {
    body: TrainerCreate;
    query?: {
        db?: unknown;
    };
};

export type CreateUserTrainerAdminTrainerCreatePostResponse = (unknown);

export type CreateUserTrainerAdminTrainerCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetTrainersAdminTrainerGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetTrainersAdminTrainerGetAllGetResponse = (ListTrainers);

export type EndpointGetTrainersAdminTrainerGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdateSportCenterAdminTrainerUpdateTrainerIdPatchData = {
    body: TrainerUpdate;
    path: {
        trainer_id: string;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdateSportCenterAdminTrainerUpdateTrainerIdPatchResponse = (TrainerUpdate);

export type EndpointUpdateSportCenterAdminTrainerUpdateTrainerIdPatchError = (unknown | HTTPValidationError);

export type EndpointDeleteDisciplinesAdminTrainerDeleteTrainerIdDeleteData = {
    path: {
        trainer_id: string;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointDeleteDisciplinesAdminTrainerDeleteTrainerIdDeleteResponse = (TrainerResponse);

export type EndpointDeleteDisciplinesAdminTrainerDeleteTrainerIdDeleteError = (unknown | HTTPValidationError);

export type EndpointTrainerToSportCenterAdminTrainerSportcenterJoinPostData = {
    body: TrainerSportcenterCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointTrainerToSportCenterAdminTrainerSportcenterJoinPostResponse = (unknown);

export type EndpointTrainerToSportCenterAdminTrainerSportcenterJoinPostError = (unknown | HTTPValidationError);

export type EndpointCreateSportCenterAdminSportCentersCreatePostData = {
    body: SportCenterCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointCreateSportCenterAdminSportCentersCreatePostResponse = (SportCenterCreate);

export type EndpointCreateSportCenterAdminSportCentersCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetSportCentersAdminSportCentersGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetSportCentersAdminSportCentersGetAllGetResponse = (ListSportCenter);

export type EndpointGetSportCentersAdminSportCentersGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdateSportCenterAdminSportCentersUpdateSportCenterIdPatchData = {
    body: SportCenterUpdate;
    path: {
        sport_center_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdateSportCenterAdminSportCentersUpdateSportCenterIdPatchResponse = (SportCenterResponse);

export type EndpointUpdateSportCenterAdminSportCentersUpdateSportCenterIdPatchError = (unknown | HTTPValidationError);

export type EndpointCreateDisciplineAdminDisciplineCreatePostData = {
    body: DisciplineCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointCreateDisciplineAdminDisciplineCreatePostResponse = (DisciplineCreate);

export type EndpointCreateDisciplineAdminDisciplineCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetDisciplinesAdminDisciplineGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetDisciplinesAdminDisciplineGetAllGetResponse = (ListDisciplineResponse);

export type EndpointGetDisciplinesAdminDisciplineGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdateDisciplineAdminDisciplineUpdateDisciplineIdPatchData = {
    body: DisciplineUpdate;
    path: {
        discipline_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdateDisciplineAdminDisciplineUpdateDisciplineIdPatchResponse = (SportCenterResponse);

export type EndpointUpdateDisciplineAdminDisciplineUpdateDisciplineIdPatchError = (unknown | HTTPValidationError);

export type EndpointDeleteDisciplinesAdminDisciplineDeleteDisciplineIdDeleteData = {
    path: {
        discipline_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointDeleteDisciplinesAdminDisciplineDeleteDisciplineIdDeleteResponse = (DisciplineBase);

export type EndpointDeleteDisciplinesAdminDisciplineDeleteDisciplineIdDeleteError = (unknown | HTTPValidationError);

export type EndpointCreateScheduleForDisciplineAdminScheduleForDisciplineCreatePostData = {
    body: ScheduleForDisciplineCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointCreateScheduleForDisciplineAdminScheduleForDisciplineCreatePostResponse = (ScheduleForDisciplineCreate);

export type EndpointCreateScheduleForDisciplineAdminScheduleForDisciplineCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetDisciplinesAdminScheduleForDisciplineGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetDisciplinesAdminScheduleForDisciplineGetAllGetResponse = (ListScheduleForDiscipline);

export type EndpointGetDisciplinesAdminScheduleForDisciplineGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdateScheduleForDisciplineAdminScheduleForDisciplineUpdateScheduleForDisciplineIdPatchData = {
    body: ScheduleForDisciplineUpdate;
    path: {
        schedule_for_discipline_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdateScheduleForDisciplineAdminScheduleForDisciplineUpdateScheduleForDisciplineIdPatchResponse = (ScheduleForDisciplineUpdate);

export type EndpointUpdateScheduleForDisciplineAdminScheduleForDisciplineUpdateScheduleForDisciplineIdPatchError = (unknown | HTTPValidationError);

export type EndpointDeleteScheduleForDisciplineAdminScheduleForDisciplineDeleteScheduleForDisciplineIdDeleteData = {
    path: {
        schedule_for_discipline_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointDeleteScheduleForDisciplineAdminScheduleForDisciplineDeleteScheduleForDisciplineIdDeleteResponse = (ScheduleForDisciplineResponse);

export type EndpointDeleteScheduleForDisciplineAdminScheduleForDisciplineDeleteScheduleForDisciplineIdDeleteError = (unknown | HTTPValidationError);

export type EndpointCreatePlanAdminPlanCreatePostData = {
    body: PlanCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointCreatePlanAdminPlanCreatePostResponse = (PlanCreate);

export type EndpointCreatePlanAdminPlanCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetPlansAdminPlanGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetPlansAdminPlanGetAllGetResponse = (ListPlan);

export type EndpointGetPlansAdminPlanGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdatePlanAdminPlanUpdatePlanIdPatchData = {
    body: PlanUpdate;
    path: {
        plan_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdatePlanAdminPlanUpdatePlanIdPatchResponse = (ScheduleForDisciplineUpdate);

export type EndpointUpdatePlanAdminPlanUpdatePlanIdPatchError = (unknown | HTTPValidationError);

export type EndpointDeletePlanAdminPlanDeletePlanIdDeleteData = {
    path: {
        plan_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointDeletePlanAdminPlanDeletePlanIdDeleteResponse = (PlanResponse);

export type EndpointDeletePlanAdminPlanDeletePlanIdDeleteError = (unknown | HTTPValidationError);

export type EndpointCreateScheduleAdminScheduleCreatePostData = {
    body: ScheduleCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointCreateScheduleAdminScheduleCreatePostResponse = (ScheduleCreate);

export type EndpointCreateScheduleAdminScheduleCreatePostError = (unknown | HTTPValidationError);

export type EndpointGetSchedulesAdminScheduleGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetSchedulesAdminScheduleGetAllGetResponse = (ListSchedule);

export type EndpointGetSchedulesAdminScheduleGetAllGetError = (unknown | HTTPValidationError);

export type EndpointUpdateScheduleAdminScheduleUpdateScheduleIdPatchData = {
    body: ScheduleUpdate;
    path: {
        schedule_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointUpdateScheduleAdminScheduleUpdateScheduleIdPatchResponse = (ScheduleUpdate);

export type EndpointUpdateScheduleAdminScheduleUpdateScheduleIdPatchError = (unknown | HTTPValidationError);

export type EndpointDeletePlanAdminScheduleDeleteScheduleIdDeleteData = {
    path: {
        schedule_id: number;
    };
    query?: {
        db?: unknown;
    };
};

export type EndpointDeletePlanAdminScheduleDeleteScheduleIdDeleteResponse = (ScheduleResponse);

export type EndpointDeletePlanAdminScheduleDeleteScheduleIdDeleteError = (unknown | HTTPValidationError);

export type EndpointStudentToSportcenterSubscriptionAdminStudentSportcenterJoinPostData = {
    body: StudentSportcenterCreate;
    query?: {
        db?: unknown;
    };
};

export type EndpointStudentToSportcenterSubscriptionAdminStudentSportcenterJoinPostResponse = (unknown);

export type EndpointStudentToSportcenterSubscriptionAdminStudentSportcenterJoinPostError = (unknown | HTTPValidationError);

export type EndpointGetStudentsAdminStudentsGetAllGetData = {
    query?: {
        db?: unknown;
    };
};

export type EndpointGetStudentsAdminStudentsGetAllGetResponse = (ListStudentSportcenter);

export type EndpointGetStudentsAdminStudentsGetAllGetError = (unknown | HTTPValidationError);

export type StudentPortalStudentStudentPortalGetData = {
    query?: {
        db?: unknown;
    };
};

export type StudentPortalStudentStudentPortalGetResponse = (unknown);

export type StudentPortalStudentStudentPortalGetError = (unknown | HTTPValidationError);

export type TrainerDashboardTrainerTrainerDashboardGetData = {
    query?: {
        db?: unknown;
    };
};

export type TrainerDashboardTrainerTrainerDashboardGetResponse = (unknown);

export type TrainerDashboardTrainerTrainerDashboardGetError = (unknown | HTTPValidationError);

export type RootGetResponse = (unknown);

export type RootGetError = unknown;